import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
  name: "Mooligan",
  projects: ["."],
  schemes: [
    // Select this in Xcode: one Cmd-U builds and runs every test target in the
    // workspace — app logic + snapshot + UI, and every feature/core module's
    // suite. See `Scheme.mooliganApp()`.
    .mooliganApp(),
  ],
  generationOptions: .options(
    // No `Mooligan-Workspace` scheme — the curated `Mooligan` scheme above is
    // the one to use, and the auto one drags in every Runner app (so one broken
    // runner breaks Cmd-U).
    autogeneratedWorkspaceSchemes: .disabled,
    // Stamps LastUpgradeCheck into every generated .xcodeproj so Xcode stops
    // raising "Update to recommended settings". Bump this when you move to a
    // new major Xcode and have reviewed its recommendations.
    lastXcodeUpgradeCheck: Version(27, 0, 0)
  )
)
