import Foundation
import ScryfallKit

public struct MockGameSetRequestClient: GameSetRequestClient {
  public static let mockSets: [MTGSet] = [
    MTGSet(
      id: UUID(uuidString: "E62111F8-C36C-495A-93FC-0C247A3E6E5F")!,
      code: "FDN",
      mtgoCode: "123",
      tcgplayerId: 1,
      name: "Test Set",
      setType: .alchemy,
      releasedAt: "19-10-1992",
      blockCode: "123",
      block: "123",
      parentSetCode: nil,
      cardCount: 10,
      printedSize: 10,
      digital: true,
      foilOnly: false,
      nonfoilOnly: false,
      scryfallUri: "scryfalURI",
      uri: "uri",
      iconSvgUri: "iconSVGURI",
      searchUri: "searchURI"
    ),
    MTGSet(
      id: UUID(uuidString: "E121E1F8-C36C-495A-93FC-0C247A3E6E5F")!,
      code: "123",
      mtgoCode: "123",
      tcgplayerId: 1,
      name: "Test Set",
      setType: .alchemy,
      releasedAt: "19-10-1992",
      blockCode: "123",
      block: "123",
      parentSetCode: nil,
      cardCount: 10,
      printedSize: 10,
      digital: true,
      foilOnly: false,
      nonfoilOnly: false,
      scryfallUri: "scryfalURI",
      uri: "uri",
      iconSvgUri: "iconSVGURI",
      searchUri: "searchURI"
    ),
    MTGSet(
      id: UUID(uuidString: "E621E1F8-C36C-495A-93FC-0C241A3E6E5F")!,
      code: "123",
      mtgoCode: "123",
      tcgplayerId: 1,
      name: "Test Set",
      setType: .alchemy,
      releasedAt: "19-10-1992",
      blockCode: "123",
      block: "123",
      parentSetCode: nil,
      cardCount: 10,
      printedSize: 10,
      digital: true,
      foilOnly: false,
      nonfoilOnly: false,
      scryfallUri: "scryfalURI",
      uri: "uri",
      iconSvgUri: "iconSVGURI",
      searchUri: "searchURI"
    ),
    MTGSet(
      id: UUID(uuidString: "E621E1F8-C36C-495A-93FC-0C247A3E6E51")!,
      code: "123",
      mtgoCode: "123",
      tcgplayerId: 1,
      name: "Test Set",
      setType: .alchemy,
      releasedAt: "19-10-1992",
      blockCode: "123",
      block: "123",
      parentSetCode: nil,
      cardCount: 10,
      printedSize: 10,
      digital: true,
      foilOnly: false,
      nonfoilOnly: false,
      scryfallUri: "scryfalURI",
      uri: "uri",
      iconSvgUri: "iconSVGURI",
      searchUri: "searchURI"
    ),
    MTGSet(
      id: UUID(uuidString: "E621E1F8-136C-495A-93FC-0C247A3E6E5F")!,
      code: "123",
      mtgoCode: "123",
      tcgplayerId: 1,
      name: "Test Set",
      setType: .alchemy,
      releasedAt: "19-10-1992",
      blockCode: "123",
      block: "123",
      parentSetCode: nil,
      cardCount: 10,
      printedSize: 10,
      digital: true,
      foilOnly: false,
      nonfoilOnly: false,
      scryfallUri: "scryfalURI",
      uri: "uri",
      iconSvgUri: "iconSVGURI",
      searchUri: "searchURI"
    )
  ]
  
  public func getAllSets() async throws -> [MTGSet] {
    MockGameSetRequestClient.mockSets
  }
}
