import ScryfallKit
import Foundation

extension Card {
  public var resolvedIconURL: URL? {
    let code = self.set.lowercased()
    let base = "https://svgs.scryfall.io/sets/"
    
    if let slug = Self.iconOverrides[code] {
      return URL(string: "\(base)\(slug)")
    }
    
    if code.count >= 4, let prefix = code.first {
      let strippedCode = String(code.dropFirst())
      
      var shouldStrip = false
      switch prefix {
      case "t":
        shouldStrip = (self.setType == .token || self.setType == .memorabilia)
      case "a":
        shouldStrip = (self.setType == .memorabilia || self.setType == .starter)
      case "b":
        shouldStrip = (self.setType == .masters)
      case "f":
        shouldStrip = (self.setType == .memorabilia)
      case "j":
        shouldStrip = (self.setType == .memorabilia)
      case "m":
        shouldStrip = (self.setType == .minigame)
      case "o":
        shouldStrip = [.archenemy, .arsenal, .box, .commander, .memorabilia, .planechase].contains(self.setType)
      case "p":
        shouldStrip = [.masterpiece, .memorabilia, .promo, .token].contains(self.setType)
      case "r":
        shouldStrip = (self.setType == .promo)
      case "s":
        shouldStrip = (self.setType == .funny || self.setType == .token)
      case "u":
        shouldStrip = (self.setType == .promo)
      case "w":
        shouldStrip = (self.setType == .token)
      default:
        break
      }
      
      if shouldStrip {
        return URL(string: "\(base)\(strippedCode).svg")
      }
    }
    
    if self.setType == .promo {
      return URL(string: "\(base)star.svg")
    }
    
    return URL(string: "\(base)\(code).svg")
  }
  
  private static let iconOverrides: [String: String] = [
    "4bb": "4ed.svg",
    "aa1": "mtga.svg",
    "aa2": "mtga.svg",
    "aa3": "mtga.svg",
    "aa4": "mtga.svg",
    "ana": "mtga.svg",
    "anb": "mtga.svg",
    "cmb1": "planeswalker.svg",
    "cmb2": "planeswalker.svg",
    "cp1": "star.svg",
    "cp2": "star.svg",
    "cp3": "star.svg",
    "cst": "csp.svg",
    "dbl": "star.svg",
    "dci": "dci.svg",
    "dvd": "ddc.svg",
    "ea1": "mtga.svg",
    "ea2": "mtga.svg",
    "ea3": "mtga.svg",
    "evg": "dd1.svg",
    "f01": "dci.svg",
    "f02": "dci.svg",
    "f03": "dci.svg",
    "f04": "dci.svg",
    "f05": "dci.svg",
    "f06": "dci.svg",
    "f07": "dci.svg",
    "f08": "dci.svg",
    "f09": "dci.svg",
    "f10": "dci.svg",
    "fbb": "3ed.svg",
    "fnm": "default.svg",
    "g00": "dci.svg",
    "g01": "dci.svg",
    "g02": "dci.svg",
    "g03": "dci.svg",
    "g04": "dci.svg",
    "g05": "dci.svg",
    "g06": "dci.svg",
    "g07": "dci.svg",
    "g08": "dci.svg",
    "g09": "dci.svg",
    "g10": "dci.svg",
    "g11": "dci.svg",
    "g17": "star.svg",
    "g18": "m19.svg",
    "g99": "default.svg",
    "gk1": "grn.svg",
    "gk2": "rna.svg",
    "gvl": "ddd.svg",
    "h1r": "mh1.svg",
    "h2r": "mh2.svg",
    "ha2": "ha1.svg",
    "ha3": "ha1.svg",
    "ha4": "ha1.svg",
    "ha5": "ha1.svg",
    "ha6": "ha1.svg",
    "ha7": "ha1.svg",
    "hho": "star.svg",
    "itp": "x2ps.svg",
    "j20": "archie.svg",
    "jgp": "default.svg",
    "jp1": "default.svg",
    "jvc": "dd2.svg",
    "l12": "default.svg",
    "l13": "default.svg",
    "l14": "default.svg",
    "l15": "default.svg",
    "l16": "default.svg",
    "l17": "default.svg",
    "lmar": "spm.svg",
    "mar": "spm.svg",
    "mgb": "vis.svg",
    "mpr": "dci.svg",
    "o90p": "star.svg",
    "oana": "mtga.svg",
    "olep": "star.svg",
    "olgc": "pmei.svg",
    "om2": "default.svg",
    "ovnt": "pmei.svg",
    "p03": "dci.svg",
    "p04": "dci.svg",
    "p05": "dci.svg",
    "p06": "dci.svg",
    "p07": "default.svg",
    "p08": "default.svg",
    "p09": "default.svg",
    "p10": "default.svg",
    "p11": "default.svg",
    "p15a": "default.svg",
    "p22": "archie.svg",
    "p23": "archie.svg",
    "p2hg": "dci.svg",
    "p30a": "star.svg",
    "p30h": "star.svg",
    "p30m": "star.svg",
    "p30t": "star.svg",
    "pa1": "mtga.svg",
    "pal00": "parl2.svg",
    "pal01": "parl2.svg",
    "pal02": "parl.svg",
    "pal03": "parl.svg",
    "pal04": "parl.svg",
    "pal05": "parl.svg",
    "pal06": "parl.svg",
    "pal99": "usg.svg",
    "palp": "papac.svg",
    "pana": "mtga.svg",
    "parl": "parl.svg",
    "pcbb": "star.svg",
    "pcel": "star.svg",
    "pcmp": "default.svg",
    "pdp10": "pmtg2.svg",
    "pdp12": "pmtg2.svg",
    "pdp13": "m13.svg",
    "pdp14": "m14.svg",
    "pdp15": "m15.svg",
    "pdrc": "pdrc.svg",
    "pdtp": "pxbox.svg",
    "pelp": "peuro.svg",
    "pewk": "star.svg",
    "pf19": "star.svg",
    "pf20": "star.svg",
    "pf23": "star.svg",
    "pf24": "star.svg",
    "pf25": "star.svg",
    "pf26": "star.svg",
    "pgpx": "star.svg",
    "pgru": "pgru.svg",
    "ph17": "star.svg",
    "ph18": "star.svg",
    "ph19": "star.svg",
    "ph20": "star.svg",
    "ph21": "star.svg",
    "ph22": "star.svg",
    "ph23": "star.svg",
    "phel": "avr.svg",
    "phop": "dci.svg",
    "phpr": "pbook.svg",
    "phtr": "star.svg",
    "pidw": "pidw.svg",
    "pj21": "archie.svg",
    "pjas": "dci.svg",
    "pjjt": "dci.svg",
    "pjsc": "star.svg",
    "pjse": "dci.svg",
    "pl21": "star.svg",
    "pl22": "star.svg",
    "pl23": "star.svg",
    "pl24": "star.svg",
    "pl25": "star.svg",
    "pl26": "star.svg",
    "plg20": "star.svg",
    "plg21": "star.svg",
    "plg22": "star.svg",
    "plg24": "star.svg",
    "plg25": "star.svg",
    "plgm": "default.svg",
    "plny": "star.svg",
    "plst": "planeswalker.svg",
    "pltc": "star.svg",
    "pmda": "star.svg",
    "pmei": "pmei.svg",
    "pmic": "past.svg",
    "pmoa": "mtgo.svg",
    "pmps": "rav.svg",
    "pmps06": "pmtg2.svg",
    "pmps07": "pmps.svg",
    "pmps08": "pmps.svg",
    "pmps09": "pmps.svg",
    "pmps10": "pmps.svg",
    "pmps11": "pmps.svg",
    "pnat": "star.svg",
    "ppc1": "m15.svg",
    "ppp1": "star.svg",
    "ppro": "star.svg",
    "pr2": "dci.svg",
    "pr23": "star.svg",
    "prcq": "star.svg",
    "pred": "default.svg",
    "prm": "mtgo.svg",
    "prw2": "rna.svg",
    "prwk": "grn.svg",
    "ps11": "psal.svg",
    "ps14": "default.svg",
    "ps15": "ori.svg",
    "ps16": "default.svg",
    "ps17": "default.svg",
    "ps18": "star.svg",
    "ps19": "war.svg",
    "psal": "phuk.svg",
    "psdc": "default.svg",
    "pspl": "star.svg",
    "pss1": "bfz.svg",
    "pss2": "star.svg",
    "pss3": "star.svg",
    "pss4": "star.svg",
    "pss5": "star.svg",
    "pssc": "default.svg",
    "psus": "dci.svg",
    "psvc": "star.svg",
    "ptbro": "bro.svg",
    "ptc": "default.svg",
    "ptdmu": "dmu.svg",
    "ptkdf": "dtk.svg",
    "ptsnc": "snc.svg",
    "punk": "planeswalker.svg",
    "purl": "star.svg",
    "pvan": "van.svg",
    "pw11": "star.svg",
    "pw12": "star.svg",
    "pw21": "star.svg",
    "pw22": "star.svg",
    "pw23": "star.svg",
    "pw24": "star.svg",
    "pw25": "star.svg",
    "pw26": "star.svg",
    "pwcs": "star.svg",
    "pwor": "default.svg",
    "pwos": "default.svg",
    "pxtc": "xln.svg",
    "q06": "star.svg",
    "q07": "star.svg",
    "rqs": "default.svg",
    "slc": "star.svg",
    "sld": "star.svg",
    "slp": "star.svg",
    "slu": "star.svg",
    "slx": "star.svg",
    "sum": "psum.svg",
    "tbth": "bng.svg",
    "tdag": "jou.svg",
    "tdvd": "ddc.svg",
    "tevg": "dd1.svg",
    "tfth": "ths.svg",
    "tgk1": "grn.svg",
    "tgk2": "rna.svg",
    "tgvl": "ddd.svg",
    "thp1": "ths.svg",
    "thp2": "bng.svg",
    "thp3": "jou.svg",
    "tjvc": "dd2.svg",
    "tmsh": "default.svg",
    "tsb": "tsp.svg",
    "ugin": "frf.svg",
    "ulst": "planeswalker.svg",
    "unk": "planeswalker.svg",
    "wc00": "default.svg",
    "wc01": "default.svg",
    "wc02": "default.svg",
    "wc03": "default.svg",
    "wc04": "default.svg",
    "wc97": "default.svg",
    "wc98": "default.svg",
    "wc99": "default.svg",
    "wdmu": "star.svg",
    "wmkm": "star.svg",
    "wwoe": "star.svg",
    "xana": "mtga.svg",
    "ymid": "y22.svg",
    "yneo": "y22.svg",
    "ysnc": "y22.svg",
    "ybro": "y23.svg",
    "ydmu": "y23.svg",
    "yone": "y23.svg",
    "ylci": "y24.svg",
    "ymkm": "y24.svg",
    "yotj": "y24.svg",
    "ywoe": "y24.svg",
    "yblb": "y25.svg",
    "ydft": "y25.svg",
    "ydsk": "y25.svg",
    "yecl": "y25.svg",
    "yeoe": "y25.svg",
    "ytdm": "y25.svg"
  ]
}
